name: Run sonar analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONAR_URL: https://sonarcloud.io
  SONAR_ORGANIZATION: telecominfraproject
  SONAR_PROJECT_KEY: Telecominfraproject_wlan-cloud-base
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: wlan-cloud-base-sonartest
    - uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-cloud-root
        path: wlan-cloud-root
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: test
      run: echo ${{ env.SONAR_URL }}
    - name: Run maven
      working-directory: wlan-cloud-base-sonartest/base-build
      run: pwd; ls -la; mvn clean verify sonar:sonar -Djvm.options=-Xss4m -Dsonar.host.url=${{ env.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
