name: Run sonar analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONAR_URL: https://sonarcloud.io
  SONAR_ORGANIZATION: telecominfraproject
  SONAR_PROJECT_KEY: wlan-cloud-base-sonartest
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: wlan-cloud-base-sonartest
        fetch-depth: 0
    - name: Checkout dependency Telecominfraproject/wlan-cloud-root
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-cloud-root
        path: wlan-cloud-root
        fetch-depth: 0
    - name: test
      run: |
        free -m
    - name: Sonar Analysis
      uses: ./wlan-cloud-base-sonartest/.github/actions/sonar
      with:
        project_dir: wlan-cloud-base-sonartest/base-build/
        sonar_args: -Dsonar.host.url=${{ env.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
