name: Run sonar analysis

on:
  push:
    branches: [ master ]

env:
  SONAR_URL: https://sonarcloud.io
  SONAR_ORGANIZATION: telecominfraproject
  SONAR_PROJECT_KEY: wlan-cloud-base-sonartest
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAVEN_OPTS: -Xmx2g # prevents java.lang.StackOverflowError
#
jobs:
  sonar:
    runs-on: ubuntu-20.04 # prevents java.lang.StackOverflowError
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: wlan-cloud-base-sonartest
        fetch-depth: 0
    - name: Checkout dependency Telecominfraproject/wlan-cloud-root
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-cloud-root
        path: wlan-cloud-root
        fetch-depth: 0
    - name: Install JDK14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk
        architecture: x64
    - name: Run sonar
      working-directory: wlan-cloud-base-sonartest/base-build
      run: |
        mvn clean verify sonar:sonar -Dsonar.host.url=${{ env.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
